apiVersion: v1
kind: Namespace
metadata:
  name: wireguard
  labels:
    name: wireguard
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-config
  namespace: wireguard
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "Africa/Cairo"
  wireguard.conf: |
    [Interface]
    Address = 10.10.10.2/24
    PrivateKey = EKWuxGsCetXFPHaC/vAfu6f8SJGd/xYYfVqAGA93LHM=
    
    [Peer]
    PublicKey = TJjtZ7hjwAYuL6c+WxVK9GyCxv/AJg5VTDa5BMaSSzY=
    AllowedIPs = 0.0.0.0/1
    Endpoint = 172.17.168.19:51820
    PersistentKeepalive = 25
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg-clnt
  namespace: wireguard
  labels:
    app: wg-clnt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wg-clnt
  template:
    metadata:
      labels:
        app: wg-clnt
    spec:
      containers:
      - name: wireguard
        image: ghcr.io/linuxserver/wireguard:latest
        envFrom:
        - configMapRef:
            name: wireguard-config 
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
          privileged: true
        volumeMounts:
          - name: configuration
            mountPath: /etc/wireguard/wireguard.conf
            subPath: wireguard.conf
          - name: host-volumes
            mountPath: /lib/modules
        ports:
        - containerPort: 51820
          protocol: UDP
      volumes:
        - name: configuration
          configMap:
            name: wireguard-config
        - name: host-volumes
          hostPath:
            path: /lib/modules
            type: Directory           
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: wg-clnt
  name: wg-clnt
  namespace: wireguard
spec:
  type: NodePort
  ports:
  - port: 51820
    nodePort: 31820
    protocol: UDP
    targetPort: 51820
  selector:
    app: wg-clnt